AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  RepositoryName:
    Type: String
    Description: The name of the repository to create
  OrganizationId:
    Type: String
    Description: The ID of the organization


Resources:
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: IMMUTABLE
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSelfManage
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: ecr:*
          - Sid: AllowPull
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
            Condition:
              StringLike:
                aws:PrincipalOrgID: !Ref OrganizationId
